_wandb:
    value:
        cli_version: 0.23.1
        code_path: source-TRM_NM_Training-pretrain.py
        e:
            5ubs0nedcwc1u8y73zghjpq2a8bq526d:
                args:
                    - --config-name=cfg_trm_nm_fast
                    - +project_name=TRM_NM_Training
                    - +run_name=trm_nm_fast_v1
                    - +checkpoint_path=/data/TinyRecursiveModels/checkpoints/trm_nm_fast_v1
                codePath: pretrain.py
                codePathLocal: pretrain.py
                email: iamseungpil@gmail.com
                executable: /data/miniforge3/envs/memgen_arc/bin/python3.10
                git:
                    commit: c8069f50a6bf54a2572189dc341b3f9bcb412fed
                    remote: https://github.com/iamseungpil/TinyRecursiveModels.git
                host: gpu-1
                os: Linux-5.15.0-141-generic-x86_64-with-glibc2.35
                program: /home/ubuntu/TinyRecursiveModels/pretrain.py
                python: CPython 3.10.19
                root: /home/ubuntu/TinyRecursiveModels
                startedAt: "2025-12-25T02:42:10.690166Z"
                writerId: 5ubs0nedcwc1u8y73zghjpq2a8bq526d
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 50
            "3":
                - 13
                - 16
                - 61
            "4": 3.10.19
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
arch:
    value:
        H_cycles: 3
        H_layers: 0
        L_cycles: 6
        L_layers: 2
        expansion: 4
        forward_dtype: bfloat16
        halt_exploration_prob: 0.1
        halt_max_steps: 16
        hidden_size: 512
        loss:
            loss_type: stablemax_cross_entropy
            name: recursive_reasoning.trm_nm@TRM_NM_ACTLossHead
        memory_hidden_mult: 4
        name: recursive_reasoning.trm_nm@TRM_NM
        no_ACT_continue: true
        num_heads: 8
        pos_encodings: rope
        puzzle_emb_len: 16
        puzzle_emb_ndim: 512
        surprise_loss_weight: 0.1
beta1:
    value: 0.9
beta2:
    value: 0.95
checkpoint_every_eval:
    value: true
checkpoint_path:
    value: /data/TinyRecursiveModels/checkpoints/trm_nm_fast_v1
data_paths:
    value:
        - data/arc-aug-1000
data_paths_test:
    value: []
ema:
    value: false
ema_rate:
    value: 0.999
epochs:
    value: 5000
eval_interval:
    value: 500
eval_save_outputs:
    value: []
evaluators:
    value:
        - name: arc@ARC
freeze_weights:
    value: false
global_batch_size:
    value: 384
load_checkpoint:
    value: null
lr:
    value: 0.0001
lr_min_ratio:
    value: 1
lr_warmup_steps:
    value: 500
min_eval_interval:
    value: 0
project_name:
    value: TRM_NM_Training
puzzle_emb_lr:
    value: 0.01
puzzle_emb_weight_decay:
    value: 0.1
run_name:
    value: trm_nm_fast_v1
seed:
    value: 0
weight_decay:
    value: 0.1
