_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 50
                - 55
                - 105
            "2":
                - 1
                - 50
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.14
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
arch:
    value:
        H_cycles: 3
        H_layers: 0
        L_cycles: 4
        L_layers: 2
        expansion: 4
        forward_dtype: bfloat16
        halt_exploration_prob: 0.1
        halt_max_steps: 16
        hidden_size: 512
        loss:
            loss_type: stablemax_cross_entropy
            name: losses@ACTLossHead
        mlp_t: false
        name: recursive_reasoning.trm@TinyRecursiveReasoningModel_ACTV1
        no_ACT_continue: true
        num_heads: 8
        pos_encodings: rope
        puzzle_emb_len: 16
        puzzle_emb_ndim: 512
beta1:
    value: 0.9
beta2:
    value: 0.95
checkpoint_every_eval:
    value: true
checkpoint_path:
    value: /data/trm/checkpoints/pretrain_att_arc1concept_4
data_paths:
    value:
        - /data/arc1concept-aug-1000
data_paths_test:
    value: []
ema:
    value: true
ema_rate:
    value: 0.999
epochs:
    value: 100000
eval_interval:
    value: 10000
eval_save_outputs:
    value: []
evaluators:
    value:
        - name: arc@ARC
freeze_weights:
    value: false
global_batch_size:
    value: 768
load_checkpoint:
    value: null
lr:
    value: 0.0001
lr_min_ratio:
    value: 1
lr_warmup_steps:
    value: 2000
min_eval_interval:
    value: 0
project_name:
    value: Arc1concept-aug-1000-ACT-torch
puzzle_emb_lr:
    value: 0.01
puzzle_emb_weight_decay:
    value: 0.1
run_name:
    value: pretrain_att_arc1concept_4
seed:
    value: 0
weight_decay:
    value: 0.1
