_wandb:
    value:
        cli_version: 0.22.2
        code_path: source-TRM_Titans_Training-pretrain.py
        e:
            aqox5c09guct7pbgxhq7vyb5d2tc64vz:
                args:
                    - --config-name
                    - cfg_trm_titans_fast
                codePath: pretrain.py
                codePathLocal: pretrain.py
                email: iamseungpil@gmail.com
                executable: /data/miniforge3/bin/python
                git:
                    commit: f630b6661c2edf85d24db78051a437020b412ed9
                    remote: https://github.com/iamseungpil/TinyRecursiveModels.git
                host: gpu-1
                os: Linux-5.15.0-141-generic-x86_64-with-glibc2.35
                program: /home/ubuntu/TinyRecursiveModels/pretrain.py
                python: CPython 3.10.14
                root: /home/ubuntu/TinyRecursiveModels
                startedAt: "2025-12-29T08:53:04.624376Z"
                writerId: aqox5c09guct7pbgxhq7vyb5d2tc64vz
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 50
                - 105
            "2":
                - 1
                - 50
                - 105
            "3":
                - 13
                - 16
                - 61
            "4": 3.10.14
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
arch:
    value:
        H_cycles: 3
        H_layers: 0
        L_cycles: 6
        L_layers: 2
        expansion: 4
        forward_dtype: bfloat16
        halt_exploration_prob: 0.1
        halt_max_steps: 16
        hidden_size: 512
        loss:
            loss_type: stablemax_cross_entropy
            name: recursive_reasoning.trm_titans@TRM_Titans_ACTLossHead
        memory_hidden_mult: 4
        name: recursive_reasoning.trm_titans@TRM_Titans
        no_ACT_continue: true
        num_heads: 8
        pos_encodings: rope
        puzzle_emb_len: 16
        puzzle_emb_ndim: 512
        surprise_loss_weight: 0.1
beta1:
    value: 0.9
beta2:
    value: 0.95
checkpoint_every_eval:
    value: true
checkpoint_path:
    value: /data/TinyRecursiveModels/checkpoints/trm_titans_fast
data_paths:
    value:
        - data/arc-aug-1000
data_paths_test:
    value:
        - data/arc-aug-1000
ema:
    value: false
ema_rate:
    value: 0.999
epochs:
    value: 128
eval_interval:
    value: 128
eval_save_outputs:
    value: []
evaluators:
    value:
        - name: arc@ARC
freeze_weights:
    value: false
global_batch_size:
    value: 192
load_checkpoint:
    value: null
lr:
    value: 0.0001
lr_min_ratio:
    value: 1
lr_warmup_steps:
    value: 50
min_eval_interval:
    value: 0
project_name:
    value: TRM_Titans_Training
puzzle_emb_lr:
    value: 0.01
puzzle_emb_weight_decay:
    value: 0.1
run_name:
    value: trm_titans_fast_v13_eval_end
seed:
    value: 0
weight_decay:
    value: 0.1
