_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
H_cycles:
    value: 3
L_cycles:
    value: 6
L_layers:
    value: 4
batch_size:
    value: 32
checkpoint_interval:
    value: 5000
data_path:
    value: /data/arc/processed
device:
    value: cuda:0
epochs:
    value: 1
eval_interval:
    value: 1000
expansion:
    value: 4
halt_exploration_prob:
    value: 0.1
halt_max_steps:
    value: 16
hidden_size:
    value: 512
log_interval:
    value: 10
lr:
    value: 0.0001
lr_min_ratio:
    value: 0.1
lr_warmup_steps:
    value: 1000
num_heads:
    value: 8
output_dir:
    value: /data/trm/pretrain
pos_encodings:
    value: rope
project_name:
    value: arc-trm-pretrain
run_name:
    value: trm_20251014_145508
seed:
    value: 42
weight_decay:
    value: 0.01
